### ISSUE TITLE
Home - Downloading video?

### ISSUE THREAD

**Issue by jmsalcido** [Nearsoft/jobs-web#25]
Seems to be downloading video 2much at: http://nearsoftjobs.com

**Comment by alebelcor** [comment]
The request to the video seems to happen over and over indefinitely as long as you have the homepage open: https://www.screencast.com/t/CL2ZoOBtbp

**Comment by jmsalcido** [comment]
still downloading a lot D:

**Comment by fhernandezn** [comment]
taking a look :) thanks guys!
