### ISSUE TITLE
Trasladar dominio propio de Medium a blog.nearsoftjobs.com c:

### ISSUE THREAD

**Issue by RockAndDors** [Nearsoft/jobs-web#56]
Berik Dossayev (Medium Support)Oct 11, 12:18 AM PDTHi jobs,Thanks for your interest in setting up a custom domain for your Medium publication.Included below are instructions for setting up your custom domain: blog.nearsoftjobs.comThis screencast will help you through the process as well: https://youtu.be/mBY7OL7T8ykIMPORTANT NOTE: If you're planning to migrate content from another platform using the same domain that you're setting up on Medium, you should migrate the content into your Medium publication PRIOR to setting up your custom domain on Medium. If you don't migrate the content first, permanent redirects from the old content will not be set up correctly. Read more about migrating content here: https://help.medium.com/hc/en-us/articles/218572107-How-to-move-to-MediumGetting StartedSetting up a custom domain consists of 3 steps:1. Adding the CNAME that you'll find below. The CNAME is used for verification and allows us to order an SSL certificate for you. It doesn't resolve to anything.2. Adding the A records that you'll find below. This is the DNS routing that points your domain or subdomain to our servers.3. Adding a CNAME that enables the subdomain www to work. (Optional) To enable www to work, add one more CNAME: www > yourdomain.com (or subdomain.yourdomain.com)If you add the CNAME and A Records at the same time, your domain will be down for a couple hours while we wait for the SSL certificate ordering process to go through. If you don't want your domain to be down at all, follow the next process:No downtime process1. Add the CNAME in step 1 below (Domain verification. Record type: CNAME). It will allow us to order an SSL cert on your behalf.2. Verify that the CNAME is set up correctly and wait for for the cert to be issued. Cert is usually issued within 1-3 hours, but can take up to 24 hours. If you can't get the CNAME set up correctly, reply to this email and we'll help you. When the cert is issued it will connect your domain to the Medium publication and if your A records are still not pointing to Medium, your medium publication URL (medium.com/yourPubURL) will return an error. Only your Medium publication is down at this point, not your domain, as it's still pointing somewhere else.3. Monitor the medium publication URL. When it stops working (usually within 1-3 hours, but can take up to 24 hours) it means that the cert is issued and the domain is connected to the publication.4. At this time, add the 12 A Records in step 2 below (DNS routing. Record type: A records).5. Your domain should now be pointing to your Medium publication and working as expected. If not, reply to this email and let us know.If a few hours of domain downtime is acceptable, or your domain is new and not used for anything yet, you can follow the process below and add the CNAME and A Records at the same time. After doing this, there will be a few hours of downtime, after which your domain will just start working. To proceed with this process, follow the instructions below:What to ModifyNote: You need to use default nameservers or enter records where your nameservers are. For example: if you bought your domain on Godaddy and use CloudFlare to manage your DNS you need to enter your records in CloudFlare.1. Domain verification. Record type: CNAMECNAME Domain (Usually located on the LEFT side in your DNS, may also be called “Host” or “Name”): 6c3e0e1a2f04ac882d5b7c1deffa12fa.blogCNAME Target (Usually located on the RIGHT side in your DNS, may also be marked “Points to” or “Value”): f578363ac7079553e0fef7b221aa4295.bcf6fe4b8c50cd8630fa572dcc0c4667.comodoca.comSome registrars add the domain part to the CNAME Domain automatically. If adding the entire string with the domain name doesn’t work, try just adding the alphanumeric string (token) before your domain. (If using a subdomain, try as "token.subdomain", and leave off the domain.) For example, Namecheap, Google domains, and Gandi all follow this token-only or token.subdomain pattern.2. DNS routing. Record type: A recordsSome registrars limit number of A records you can add. It will work with 1 A record. We need 12 for reliability and we suggest to add all of them.A Records:52.0.16.11852.1.119.17052.1.147.20552.1.173.20352.4.145.11952.4.175.11152.4.225.12452.4.240.22152.4.38.7052.5.181.7952.6.3.19252.6.46.142If you are prompted to add a “Name” for the above values, you will enter either the “@” symbol (no quotes), or the domain or subdomain name of your site.3. www redirect (Optional). Record type: CNAMEPlease note, your domain or subdomain with the “www” prefix will not work by default. If you’d like to have visitors be able to use the “www” (www.yourdomain.com or www.subdomain.yourdomain.com) prefix in addition to using your domain or subdomain directly, you will have to create a new CNAME record:domain/host/name: wwwtarget/points to/value: yourdomain.com (or @)for subdomain:domain/host/name: www (or www.subdomain in some cases)target/points to/value: subdomain.yourdomain.comIt doesn't work immediately. When you’ve successfully entered these new values, it generally takes 1-3 hours (in rare cases it can take up to 24 hours) for your domain to begin working with Medium. It's normal for you to see a certificate error or a redirect to medium.com while the certificate is being provisioned.Examples & More InfoFor a screenshot of these values correctly entered for an example domain on an example registrar, look at the following post in our Help Center.Below you can additionally find help documentation about how to add CNAME and A records for some of the more popular registrars:NamecheapGodaddyGandiGoogleIf you’ve done all the above and it’s still not working after 24 hours, reply to this email with details and we’ll help you find the solution.Thanks and we’re looking forward to having you on Medium!Thanks,BerikUser Services
--

**Comment by echavezNS** [comment]
Done :)
