### ISSUE TITLE
Use node-sass instead of ruby sass

### ISSUE THREAD

**Issue by alebelcor** [Nearsoft/jobs-web#7]
Is there a specific reason why we're using the ruby version of Sass?

If not, then we should switch to using [`grunt-sass`](https://github.com/sindresorhus/grunt-sass) instead.

This has at least two major advantages:

1. Faster Sass compilation
2. Removes the Ruby dependency, thus making this project a Node.js-only setup.

**Comment by echavezNS** [comment]
@alebelcor Do you mean to change `grunt-contrib-sass` with `grunt-sass` ?

**Comment by alebelcor** [comment]
Yes.

**Comment by echavezNS** [comment]
Done :)

**Comment by alebelcor** [comment]
Would you mind also removing these lines from `README.md`?

```txt
Install Ruby (e.g. using rbenv)
```

and

```txt
gem install sass     # install sass
```

**Comment by echavezNS** [comment]
Oh, yes I forgot about that.
